### ISSUE TITLE
enforce usage of a salt in CType json schema for enhanced privacy

### ISSUE THREAD

**Issue by brenzi** [KILTprotocol/ctype-index#3]
For privacy reasons, CTypes should all contain a salt property.

Imagine I want a verifiable credential about my [driver's license](https://github.com/KILTprotocol/ctype-index/blob/main/ctypes/0x3112e1e3fb387e5eb6c109aa45afc7ed9df01f1c90a976a8b00585abf817ca82/ctype.json) which includes my name and my birthday.

Now, I disclose this credential only selectively, however, the hash of the fields in the CType are published onchain [upon attestation](https://docs.kilt.io/docs/develop/sdk/cookbook/claiming/attestation-creation/)

The privacy issue is:

If I know your name, I can try brute-forcing all birthdays of the last 100 years in a few seconds and voilà, I know your age
there are other linkability risks as well with committing CType hashes onchain, but this one is the most simple to expose and the most simple to prevent.

One way out is to introduce entropy into the hashed payload. It is up to the creator of the credential to make use of the salt or not. But as CTypes strictly enforce the schema, I think the schema should enforce the salt property to promote best practices

http://kilt-protocol.org/draft-01/ctype#

**Comment by weichweich** [comment]
Hi, each property in a credential is hashed together with a salt. You would therefore need to guess the birthday and the salt.
The issue you raised is solved on the credential level and not on the CType level.

Here is a credential which states that I own this GitHub account. There is a `claimNonceMap` which contains the salts/nonce for each property.

```
{
    "claim": {
        "cTypeHash": "0xad52bd7a8bd8a52e03181a99d2743e00d0a5e96fdc0182626655fcf0c0a776d0",
        "contents": {
            "Username": "weichweich",
            "User ID": "14820950"
        },
        "owner": "did:kilt:4oRpCrgm4XmsvnPA8HnH5qh7FxQbU7yBgjvjv91PsCSYVydN"
    },
    "claimHashes": [
        "0x22cd533c36b37d5846f54ff0e37c1a39cdd5d93751f940edbc46a8fbde388962",
        "0x9d30c405c29686156cc74d552b97ebad38820c9d117bd125084d43a490407bd3",
        "0xc676bdbfa55333e591b249c60864bdf889aaec7dae38813061db5d057837a277"
    ],
    "claimNonceMap": {
        "0xc6cd5e369f2492848afdbffe084e96c011445ac4b8d38f2ab687599e36c9d764": "5cd1577f-5721-4645-a5b3-00b0a29a8ff8",
        "0x19e3c55144a04e5ed8b596170511034553276d35e46af09e3be13ad0aded598f": "0e5b89b9-517c-4ed5-8636-9769132de8fb",
        "0x78dda67c97302f96000447374b2e6a25c876f17fd372ca3f846684579bbbae68": "d1db2126-57a2-4849-b0e0-84ca577977c8"
    },
    "legitimations": [],
    "delegationId": null,
    "rootHash": "0xa20b5d28bdb4559763f1134d04548982be1f302254363bc5414fb8dcf67b82df",
    "claimerSignature": {
        "signature": "0x806900f07440fde6f8aeecb5328f98e4c96e6258bf8ef0c97166990aa3a1985d78d25b3ed8776df27c9cb565bb3074d4dec0ef8b51486f47cd3a93d918598a83",
        "keyId": "did:kilt:4oRpCrgm4XmsvnPA8HnH5qh7FxQbU7yBgjvjv91PsCSYVydN#0xa95a939747be4072afabb8c51331f31c0654f1a50f88e1237bd3f963996f7f14"
    }
}
```
